masagao/potfy

app/Comment.php, app/Company.php, app/Portfolio.php, app/PortfolioTechnology.php, app/Technology.php, config/database.php, database/migrations/2020_08_06_021634_create_portfolios_table.php, database/migrations/2020_08_06_021704_create_comments_table.php, database/migrations/2020_08_06_022251_create_companies_table.php, database/migrations/2020_08_06_022320_create_technologies_table.php, database/migrations/2020_08_06_022337_create_portfolio_technologies_table.php, resources/views/welcome.blade.php
＃potfyのマイグレーションファイルの作成を行いました。
以下コードをご確認の上、修正等がありましたコメント頂けたらと思います。
よろしくお願いします。
=> マイグレーションファイルの作成

database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2020_08_08_080418_create_portfolios_table.php, database/migrations/2020_08_08_080439_create_comments_table.php, database/migrations/2020_08_08_081751_create_companies_table.php, database/migrations/2020_08_08_082001_create_technologies_table.php, database/migrations/2020_08_08_082147_create_portfolio_technology_table.php
マイグレーションを追加しました。
修正箇所等ありましたら、コメント頂けたらと思います。
=> Additional Migrations

app/Http/Controllers/User/CommentController.php, app/Http/Controllers/User/PortfolioController.php
#35 
- middlewareをルーティングだけに統一した。
=> middlewareをルーティングだけで統一したい。

app/Http/Controllers/User/Auth/LoginController.php, app/Http/Controllers/User/Auth/RegisterController.php, app/Http/Controllers/User/PortfolioController.php, app/Http/Requests/PortfolioRequest.php, app/Providers/RouteServiceProvider.php, composer.json, composer.lock, config/app.php, config/cloudder.php, resources/views/user/portfolios/create.blade.php, resources/views/user/portfolios/edit.blade.php, resources/views/user/portfolios/show.blade.php, resources/views/welcome.blade.php
ポートフォリオ に画像機能を追加（クラウディナリー）を追加しました。確認よろしくお願いします。
=> ポートフォリオ に画像機能を追加（クラウディナリー）

app/Http/Controllers/Company/CompanyController.php, app/Http/Requests/CompanyRequest.php, config/database.php, resources/views/company/edit.blade.php, resources/views/company/show.blade.php, resources/views/layouts/company/app.blade.php, routes/web.php
=> #31-confirm-company-page-after-login

database/seeds/DatabaseSeeder.php, database/seeds/TechnologiesTableSeeder.php
#issue
#13 
#やったこと
technologiestableseederの作成
=> technologies_seeder

app/Http/Controllers/User/UserController.php, resources/views/user/show.blade.php
#50 
- エンジニアマイページでポートフォリオ一覧を表示できるようにしました。
=> エンジニアマイページに自分のポートフォリオを掲載したい

resources/views/user/portfolios/index.blade.php, resources/views/user/show.blade.php
#66 
- タブレットサイズでポートフォリオ一覧を2カラムに変更しました。
=> ポートフォリオ一覧画面のタブレットでの表示を修正したい

database/migrations/2020_08_28_123908_add_visited_count_to_portfolios_table.php
#issue
#54 
#やったこと
ポートフォリオテーブルにvisited_countカラム追加
=> ポートフォリオテーブルのカラム追加 

app/Http/Controllers/User/PortfolioController.php, app/Portfolio.php, resources/views/user/portfolios/show.blade.php
=> テキストエリア内にあるリンクをaタグに置換する

app/Http/Controllers/User/PortfolioController.php
#issue 
#80 
#やったこと
自分の投稿へのアクセスは閲覧数としてはカウントしない
=> 自分の投稿へのアクセスは閲覧数としてはカウントしない 

resources/views/top.blade.php
- #95 
- トップページの右のはしの空白がなくなっている
=> トップページの横スクロールを修正する

resources/views/user/portfolios/show.blade.php
- [自分の投稿の詳細以外では、編集ボタンと削除ボタンを出さない  ]
- #78
=> 自分の投稿の詳細以外では、編集ボタンと削除ボタンを出さない 

app/Http/Controllers/User/HistoryController.php, app/Http/Requests/HistoryRequest.php, resources/views/user/portfolios/show.blade.php, routes/web.php
=> 開発履歴を新規投稿できる

public/assets/js/app.js, resources/js/app.js, resources/js/components/UrlCopyComponent.vue, resources/views/user/portfolios/show.blade.php
- #52 
- URLコピーボタンを押すことで、URLをコピーできる。
=> ポートフォリオのURLを共有しやすくする

app/Http/Controllers/TermsController.php, resources/views/layouts/footer.blade.php, resources/views/terms/organizer.blade.php, resources/views/terms/privacy.blade.php, resources/views/terms/services.blade.php, routes/web.php
=> Terms ページの大枠の作成 と ページ遷移 

app/Portfolio.php, composer.json, composer.lock, database/migrations/2020_08_08_080418_create_portfolios_table.php, database/migrations/2020_08_08_080439_create_comments_table.php, database/migrations/2020_08_08_082147_create_portfolio_technology_table.php, database/migrations/2020_09_02_023919_create_histories_table.php, database/migrations/2020_09_02_030511_create_stories_table.php, public/assets/css/app.css, public/assets/js/app.js, resources/views/user/portfolios/show.blade.php
...
- #49 
- UUIDで実装してみましたが、いかがでしょうか？
=> ポートフォリオのurlをランダム文字列（数列）にしたい #49

.github/issue-branch.yml
=> Github Apps の test を行う

README.md
=> README.mdを改良したい。

public/assets/js/app.js, resources/js/components/UrlCopyComponent.vue
- #109 
- ポートフォリオ詳細画面のURLコピーをクリックするとURLがコピーされる。
=> URLのコピーのinputタグを消す。

resources/views/top.blade.php, resources/views/user/portfolios/index.blade.php, resources/views/user/profiles/show.blade.php
=> ポートフォリオカードに投稿ユーザー情報を表示して、ユーザー詳細に飛べる

app/Portfolio.php
=> ポートフォリオの文字列リンク化の軽微な修正 

app/Http/Controllers/User/Auth/LoginController.php, composer.json, composer.lock, config/services.php, resources/views/user/auth/login.blade.php, resources/views/user/auth/register.blade.php, routes/web.php
- #128 
- envに登録すれば、GitHubでログインできる
=> GitHubログイン機能

app/Enums/SocialType.php, database/migrations/2020_09_12_221054_create_social_accounts_table.php
- #105 
- migrate
- migrate:rollback
- テーブルが作成される
=> social_accountsテーブルを作成する

app/Http/Controllers/User/Auth/LoginController.php, app/SocialAccount.php
- #129 
- Twitterで新規作成した際に、social_accountsテーブルにURLのレコードが自動で生成される
=> Twitterログインをした際に、マイページURLがsocial_accountsに保存できる

app/Enums/SocialType.php, app/Http/Controllers/User/UserController.php, app/User.php, resources/lang/ja/enums.php, resources/views/user/profiles/edit.blade.php, resources/views/user/profiles/show.blade.php
- #131 
- socialアカウントを設定、閲覧できる
=> ユーザーはsocial_accountをマイページで登録、編集できる 

app/Portfolio.php, resources/views/user/portfolios/show.blade.php, resources/views/user/profiles/show.blade.php
=> aタグでtailwindcssが効き、文字が黒いので修正したい。

app/Http/Requests/PortfolioRequest.php, database/migrations/2020_08_08_080418_create_portfolios_table.php
=> portfolio投稿のリンクをnullableに

public/assets/js/app.js, resources/js/components/UrlCopyComponent.vue, resources/views/user/portfolios/show.blade.php
=> Twitter Share Button 設置 + ボタンを整列させる

app/Http/Controllers/User/PortfolioController.php, app/Http/Controllers/User/UserController.php, app/User.php, resources/views/user/profiles/edit.blade.php, resources/views/user/profiles/show.blade.php
=> ユーザーが自身の情報を登録できる。

resources/views/user/portfolios/show.blade.php
=> カード詳細のUIを整える

resources/views/top.blade.php, resources/views/user/portfolios/index.blade.php, resources/views/user/profiles/show.blade.php
=> cardのユーザーの名前が空の時、ゲスト+idを表示

resources/views/user/portfolios/show.blade.php
=> issue-167-potfy

app/Http/Controllers/User/PortfolioController.php, resources/views/user/portfolios/edit.blade.php, resources/views/user/portfolios/show.blade.php
=> issue-169-potfy

app/Http/Controllers/User/PortfolioController.php, resources/views/layouts/user/nav.blade.php
- [top take(4)→take(3) ]
- # 166
=> Index の 表示 に関して、UI の 変更に伴って 新着投稿 と 人気投稿 を 3 * 3 で表示したい

resources/views/user/auth/login.blade.php, resources/views/user/auth/register.blade.php
- [aタグが青くなっていない為、青くする。 ]
- # 172
=> aタグが青くなっていない為、青くしたい。

resources/views/layouts/user/nav.blade.php
- [新規投稿ボタンは、ログイン中のユーザーのみ見えるようにする ]
- # 174
=> 新規投稿ボタンは、ログイン中のユーザーのみ見えるようにしたい 

resources/views/layouts/user/nav.blade.php
- [ユーザーアイコンタブ、マイページとログアウトの順序を変えた ]
- # 173
=> ユーザーアイコンタブ、マイページとログアウトの順序を変えたい 

resources/views/layouts/user/nav.blade.php, resources/views/user/portfolios/show.blade.php
- [ 他人の投稿を詳細画面でtweetできる]
- # 177
=> 他人の投稿を詳細画面でtweetできる

.github/wip.yml, app/Comment.php, app/History.php, app/Portfolio.php, app/Story.php, app/User.php
=> 外部リンクに遷移する際に、一応警告を表示したい #187

resources/views/user/portfolios/show.blade.php
- #184
- 自分の投稿ではtwitterでシェアボタンを出さない
=> 自分の投稿での Twitter シェア を表示しないようにしたい

resources/views/layouts/app.blade.php, resources/views/user/portfolios/show.blade.php
- #191
- ポートフォリオ詳細のヘッダーが出ていないので、出す
=> ポートフォリオ詳細のヘッダーが出ていないので、出す

resources/views/layouts/user/nav.blade.php
=> ポートフォリオ新規投稿ボタンを丸くする

app/Http/Controllers/User/PortfolioController.php
- [ポートフォリオ一覧画面のページネーションを12で付けたい ]
- # 199
- issueの内容理解が不十分の可能性がありますのでコードの確認をよろしくお願いします。
=> ポートフォリオ一覧画面のページネーションを12で付けたい

resources/lang/ja/enums.php
- #207 
- ストーリー投稿時のタイプの文言を分かりやすく変更した
=> ストーリー投稿時のタイプの文言を分かりやすくしたい

resources/views/user/portfolios/show.blade.php
=> 開発履歴、ストーリーを投稿者のみが投稿できるようにしました

.github/workflows/opened-pulls-wip.yml, resources/views/components/portfolio-card.blade.php, resources/views/layouts/user/nav.blade.php, resources/views/user/portfolios/show.blade.php
=> ストーリーやコメント、開発履歴に投稿者の名前が表示されていない

resources/views/user/portfolios/show.blade.php
=> サービス内の投稿日時等の時間表示のフォーマットを diffForHumans(Carbon\Carbon::now()) で統一したい

.github/issue-states.yml, .github/workflows/opened-pull-wip.yml, resources/views/user/portfolios/show.blade.php
=> Twitter 拡散機能においては、GAOGAOGATE を表示しないようにする

resources/views/user/portfolios/show.blade.php
=> ポートフォリオ詳細のUIを整える

resources/views/user/portfolios/show.blade.php
=> 開発履歴や、ストーリーがないときに、現在投稿はありませんと表示できるようにする

app/Http/Controllers/User/UserController.php, resources/views/user/portfolios/show.blade.php, resources/views/user/profiles/show.blade.php
=> ユーザー詳細ページには、該当ユーザーの投稿が表示されるようにする

app/Http/Controllers/User/PortfolioController.php, app/Http/Requests/PortfolioRequest.php, app/Technology.php, database/migrations/2020_08_17_064050_change_link_add_image_path_and_public_id_to_portfolios_table.php, package-lock.json, package.json, public/assets/css/app.css, public/assets/js/app.js, resources/js/app.js, resources/js/components/SelectComponent.vue, resources/views/user/portfolios/create.blade.php, resources/views/user/portfolios/edit.blade.php
=> 技術タグをdatalistで表示し、同一の物は新規作成されないようにする

app/Http/Controllers/User/StoryController.php, app/Story.php
- connects #185 
- Storyが更新される
=> Story コメント は UpdateOrCreate で実装したい

resources/views/user/portfolios/show.blade.php
=> ゲストにはコメント欄を表示しない

public/assets/css/app.css, public/assets/js/app.js, resources/views/user/auth/login.blade.php, resources/views/user/auth/register.blade.php, tailwind.config.js
=> 新規登録画面のUIを整えたい 

resources/views/user/profiles/show.blade.php
=> ユーザー詳細のプロフィール編集ボタンは、ログインユーザーのみに表示する

public/assets/js/app.js, resources/js/components/SelectComponent.vue, resources/views/user/auth/login.blade.php, resources/views/user/auth/register.blade.php
=> ポートフォリオ編集、新規投稿（言語複数選択にプレイスホルダーを設定したい） 

resources/views/user/portfolios/show.blade.php, resources/views/user/profiles/edit.blade.php, resources/views/user/profiles/show.blade.php
=> aタグが青くなっていないため、ボタンを押せるのかを判断しにくい 

app/User.php, database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2020_08_08_080418_create_portfolios_table.php, database/migrations/2020_08_08_080439_create_comments_table.php, database/migrations/2020_09_02_023919_create_histories_table.php, database/migrations/2020_09_02_030511_create_stories_table.php, database/migrations/2020_09_12_215051_create_career_directions_table.php, database/migrations/2020_09_12_221054_create_social_accounts_table.php
- connects #225 
- この実装で問題ないでしょうか？
=> ユーザーIDに関してもランダムな文字数列に変更したい。 #225

app/Http/Controllers/User/CommentController.php, app/Http/Controllers/User/HistoryController.php, app/Http/Controllers/User/StoryController.php, resources/views/user/portfolios/_comment-modal.blade.php, resources/views/user/portfolios/_history-modal.blade.php, resources/views/user/portfolios/_story-modal.blade.php, resources/views/user/portfolios/show.blade.php
=> コメント、開発履歴、ストーリー、でモーダル、三本線でカッコよくする。

resources/views/user/portfolios/edit.blade.php, resources/views/user/profiles/edit.blade.php, resources/views/user/profiles/show.blade.php
=> マイページ詳細画面で、画像の設定がない場合にdefaultの画像が出せる

app/Http/Controllers/User/PortfolioController.php
=> ポートフォリオの画像保存サイズを修正

resources/views/user/profiles/show.blade.php
=> ユーザー詳細画面で、紹介文に改行が反映されていないので、反映させる

database/seeds/TechnologiesTableSeeder.php, public/assets/js/app.js, resources/js/components/SelectComponent.vue, resources/views/user/portfolios/create.blade.php, resources/views/user/portfolios/edit.blade.php, resources/views/user/portfolios/show.blade.php
=> 技術タグをみやすく表示したい・oldの反映

resources/views/user/portfolios/show.blade.php, resources/views/user/profiles/edit.blade.php
=> ユーザー編集画面のユーザー画像を正円で表示できる

app/Http/Controllers/User/CommentController.php, app/Http/Controllers/User/HistoryController.php, app/Http/Requests/CommentRequest.php, app/Http/Requests/HistoryRequest.php, app/Http/Requests/StoryRequest.php, resources/lang/ja/validation.php
=> ストーリー、開発履歴、コメントのエラーメッセージ日本語化

app/Http/Controllers/User/Auth/ForgotPasswordController.php, app/Http/Controllers/User/Auth/ResetPasswordController.php, app/Notifications/PasswordResetNotification.php, app/User.php, resources/views/user/auth/login.blade.php, resources/views/user/auth/passwords/email.blade.php, resources/views/user/auth/passwords/reset.blade.php, routes/web.php
- connects #241 
- デザインは一旦変えてません
=> パスワード変更機能（Gmail）

app/Http/Controllers/User/PortfolioController.php, resources/views/user/portfolios/show.blade.php
=> view側で繰り返し登場する条件式を、変数に変更する

app/Portfolio.php, app/User.php, composer.json, composer.lock
=> uuidが長すぎるので短くしたい。

resources/views/top.blade.php
=> トップページの見出しUIの修正

resources/views/terms/organizer.blade.php
- connects #278 
- 運営メンバーチームUIの軽微な修正
=> 運営メンバーチームUIの軽微な修正
